# Generated by Django 3.2.7 on 2021-12-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Doador', 'Donor'), ('Beneficiário', 'Donee')], default='Beneficiário', max_length=50, verbose_name='Roles'),
        ),
    ]
