# Generated by Django 3.2.7 on 2021-10-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_auto_20211030_1345'),
        ('accounts', '0004_auto_20211030_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campanha',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campanha.campanha'),
        ),
    ]
