# Generated by Django 3.2.7 on 2021-10-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_campanha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='campanha',
        ),
    ]
