# Generated by Django 3.2.8 on 2021-10-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('beneficiados', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DadosCadastrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('cnpj', models.CharField(max_length=18)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.campanha', verbose_name='Id_campanha')),
            ],
        ),
        migrations.CreateModel(
            name='EntidadeOrganizadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.campanha', verbose_name='Campanha')),
                ('dadosCadastrais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campanha.dadoscadastrais', verbose_name='Relacionamento_dados/entidade')),
            ],
        ),
        migrations.CreateModel(
            name='DuracaoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='inicio da campanha')),
                ('fim', models.DateField(verbose_name='fim da campanha')),
                ('campanha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campanha.campanha', verbose_name='Relacionamento_Duração/Campanha')),
            ],
        ),
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doacao', models.CharField(max_length=100)),
                ('quantidade', models.CharField(max_length=10)),
                ('dadosCadastrais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campanha.dadoscadastrais', verbose_name='Relacionamento_dados/doador')),
            ],
        ),
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=100, verbose_name='Item a ser doado')),
                ('quantidade', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('observacao', models.CharField(blank=True, max_length=300, null=True)),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campanha.meta', verbose_name='Id_Meta')),
            ],
        ),
        migrations.AddField(
            model_name='campanha',
            name='doadores',
            field=models.ManyToManyField(to='campanha.Doador'),
        ),
    ]
