# Generated by Django 3.2.7 on 2021-12-06 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='donee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
    ]
