# Generated by Django 3.2.7 on 2021-10-30 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campanha',
            name='donee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='donee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campanha',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
    ]
