# Generated by Django 3.2.7 on 2021-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_auto_20211206_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
