# Generated by Django 3.2.7 on 2021-10-30 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campanha', '0002_auto_20211030_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='campanha',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=8, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='donee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campanha',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donor', to=settings.AUTH_USER_MODEL),
        ),
    ]
