# Generated by Django 3.2.7 on 2021-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0003_alter_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneeneed',
            name='need',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
