# Generated by Django 3.2.7 on 2021-10-30 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0003_auto_20211030_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanha',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
