# Generated by Django 3.2.7 on 2021-11-27 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0005_donationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitem',
            name='campanha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donationItem', to='campanha.campanha'),
        ),
        migrations.AddConstraint(
            model_name='campanha',
            constraint=models.UniqueConstraint(fields=('name',), name='unique name'),
        ),
    ]
