# Generated by Django 3.2.7 on 2021-11-30 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0007_doneeneed_post'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campanha',
            name='unique name',
        ),
        migrations.AlterField(
            model_name='campanha',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled'), ('Pending Donee Confirmation', 'Pending Donee Confirmation')], default='Enabled', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='campanha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campanha', to='campanha.campanha'),
        ),
    ]
